2020-04-09 10:38:46,606 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 10:38:52,746 ERROR: Exception on /main/user/milo [GET] [in /home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py: 1891]
Traceback (most recent call last):
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/centvr/Documents/pyscript/microblog/app/main/routes.py", line 50, in user
    next_url=next_url,prev_url=prev_url)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/centvr/Documents/pyscript/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/centvr/Documents/pyscript/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 11, in block "html"
    {%- endblock metas %}
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "body"
    {%- block styles %}
  File "/home/centvr/Documents/pyscript/microblog/app/templates/base.html", line 75, in block "content"
    <span id="{{ task.id }}-progress">{{ task.get_progress() }}</span>%
  File "/home/centvr/Documents/pyscript/microblog/app/models.py", line 190, in get_progress
    job = self.get_rq_job()
  File "/home/centvr/Documents/pyscript/microblog/app/models.py", line 184, in get_rq_job
    rq_job = rq.job.Job.fetch(self.id,connection=currernt_app.redis)
NameError: name 'currernt_app' is not defined
2020-04-09 10:40:34,381 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 10:45:11,413 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 10:47:46,925 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 10:54:33,342 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 10:56:44,138 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 11:06:36,686 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 11:07:22,357 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 11:09:05,150 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 11:09:19,020 INFO: Microblog startup [in ./app/__init__.py: 72]
2020-04-09 11:09:34,844 ERROR: Unhandled exception [in ./app/tasks.py: 56]
Traceback (most recent call last):
  File "./app/tasks.py", line 50, in export_posts
    text_body=render_template('emaiil/export_posts.txt',user=user),
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/loaders.py", line 117, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: emaiil/export_posts.txt
2020-04-09 11:10:11,203 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 11:11:35,464 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 11:11:49,297 INFO: Microblog startup [in ./app/__init__.py: 72]
2020-04-09 11:12:05,172 ERROR: Unhandled exception [in ./app/tasks.py: 56]
Traceback (most recent call last):
  File "./app/tasks.py", line 50, in export_posts
    text_body=render_template('email/export_posts.txt',user=user),
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/centvr/Documents/pyscript/microblog/app/templates/email/export_posts.txt", line 3, in template
    {{ _('Please find attached the archive of your posts that you requested') }}.
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'Please'
2020-04-09 11:17:39,175 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 11:29:15,861 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 11:31:28,678 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 11:39:37,770 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 11:47:54,131 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 11:49:12,387 INFO: Microblog startup [in ./app/__init__.py: 72]
