2020-04-09 11:49:30,970 ERROR: Unhandled exception [in ./app/tasks.py: 56]
Traceback (most recent call last):
  File "./app/tasks.py", line 50, in export_posts
    text_body=render_template('email/export_posts.txt',user=user),
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/centvr/Documents/pyscript/microblog/app/templates/email/export_posts.txt", line 3, in template
    {{ _('Please find attached the archive of your posts that you requested') }}.
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'Please'
2020-04-09 12:00:32,101 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 12:00:58,541 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 12:04:18,655 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 12:04:37,552 INFO: Microblog startup [in ./app/__init__.py: 72]
2020-04-09 12:04:53,028 ERROR: Unhandled exception [in ./app/tasks.py: 56]
Traceback (most recent call last):
  File "./app/tasks.py", line 50, in export_posts
    text_body=render_template('email/export_posts.txt',user=user),
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/centvr/Documents/pyscript/microblog/app/templates/email/export_posts.txt", line 3, in template
    {{ _('Please find attached the archive of your posts that you requested') }}.
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'Please'
2020-04-09 12:10:15,040 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 12:11:50,957 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 12:12:05,881 INFO: Microblog startup [in ./app/__init__.py: 72]
2020-04-09 12:12:21,257 ERROR: Unhandled exception [in ./app/tasks.py: 56]
Traceback (most recent call last):
  File "./app/tasks.py", line 50, in export_posts
    text_body=render_template('email/export_posts.txt',user=user),
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/centvr/Documents/pyscript/microblog/app/templates/email/export_posts.txt", line 3, in template
    {{ _('Please find attached the archive of your posts that you requested') }}.
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'Please'
2020-04-09 12:22:36,659 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 12:23:21,448 INFO: Microblog startup [in ./app/__init__.py: 72]
2020-04-09 12:23:37,223 ERROR: Unhandled exception [in ./app/tasks.py: 56]
Traceback (most recent call last):
  File "./app/tasks.py", line 50, in export_posts
    text_body=render_template('email/export_posts.txt',user=user),
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/centvr/Documents/pyscript/microblog/app/templates/email/export_posts.txt", line 1, in top-level template code
    {{ _('Dear') }} {{ user.username }},
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/jinja2/ext.py", line 150, in gettext
    rv = __context.call(func, __string)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask_babel/__init__.py", line 110, in <lambda>
    lambda x: get_translations().ugettext(x),
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask_babel/__init__.py", line 221, in get_translations
    [get_locale()],
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask_babel/__init__.py", line 251, in get_locale
    rv = babel.locale_selector_func()
  File "./app/__init__.py", line 79, in get_locale
    return request.accept_languages.best_match(current_app.config['LANGUAGES'])
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/globals.py", line 38, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
2020-04-09 12:27:13,222 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 12:31:20,639 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 72]
2020-04-09 12:32:12,427 INFO: Microblog startup [in ./app/__init__.py: 72]
