2020-04-07 16:16:56,685 ERROR: Exception on /main/notifications [GET] [in /home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py: 1891]
Traceback (most recent call last):
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/centvr/Documents/pyscript/microblog/app/main/routes.py", line 177, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
2020-04-07 16:17:06,926 ERROR: Exception on /main/notifications [GET] [in /home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py: 1891]
Traceback (most recent call last):
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/centvr/Documents/pyscript/microblog/app/main/routes.py", line 177, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
2020-04-07 16:17:13,036 ERROR: Exception on /main/notifications [GET] [in /home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py: 1891]
Traceback (most recent call last):
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/centvr/Documents/pyscript/microblog/app/main/routes.py", line 177, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
2020-04-07 16:17:16,907 ERROR: Exception on /main/notifications [GET] [in /home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py: 1891]
Traceback (most recent call last):
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/centvr/Documents/pyscript/microblog/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/centvr/Documents/pyscript/microblog/app/main/routes.py", line 177, in notifications
    Notification.timestamp > since).order_by(Notification.timestamp.asc())
NameError: name 'Notification' is not defined
2020-04-07 16:20:30,076 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 16:32:08,492 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 17:05:19,339 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 17:31:00,760 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 17:50:56,785 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-07 18:05:47,794 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 08:48:44,458 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 09:23:55,347 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 09:56:02,552 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 10:10:19,076 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 10:30:44,113 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 10:32:36,704 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 10:34:19,108 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 10:36:48,037 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 10:55:22,588 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 11:10:50,869 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 11:15:29,432 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 11:18:05,328 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 11:37:46,665 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 11:41:03,731 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 11:44:05,049 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 11:45:30,702 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 11:51:17,305 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 11:52:53,192 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 11:55:15,970 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 11:56:54,739 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 11:58:10,043 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 13:31:15,040 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 14:03:54,606 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 14:04:07,798 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 68]
2020-04-08 16:08:19,522 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 70]
2020-04-08 16:08:46,046 INFO: Microblog startup [in /home/centvr/Documents/pyscript/microblog/app/__init__.py: 70]
